// ## Task to save the grunt.filerev.summary variable generated by filerev to disk
// This task produce an `assets.json` file which reference original and renamed version of files
// It is used to replace references of file name in css files
module.exports = function(grunt){
    return {
        dist: {
            options: {
                dest: grunt.config('settings.tmp') + '/assets/assets.json',
                cwd: grunt.config('settings.dist') + '/' // strip the build prefix from the report on disk
            }
        }
    };
};